Modified modal controller
Grupo-AFAL/frontend-helpers pull request #149
Opened 2021-11-17 22:05 UTC by M4T4

2021-11-17 22:07 UTC, M4T4 commented on app/assets/stylesheets/fe_modal.scss
> +    width: 812px;
En este caso no sabia si mantener las variables y hacer una suma especifica de pixeles para los otros tamaños.

Aqui decidi mantenerlo todo especifico.

2021-11-17 22:09 UTC, M4T4 commented
Para actualizar los los metodos que utilizen `link_to_modal` con `data: { wide: true }

Se tiene que cambiar a `data: { class: 'wide' }`

2021-11-18 02:16 UTC, fedegl commented on app/assets/stylesheets/fe_modal.scss
> +    width: 408px;
que te parece si usamos rems y lo redondeamos un poco. Aqui sugiero usar **25rem** que equivale a 400px

2021-11-18 02:16 UTC, fedegl commented on app/assets/stylesheets/fe_modal.scss
> +    width: 812px;
aqui diria usar **50rem** que equivale a 800px

2021-11-18 02:22 UTC, fedegl commented on app/assets/stylesheets/fe_modal.scss
> +    width: 1109px;
aqui diria usar **70rem** que equivale a 1120px

2021-11-18 02:22 UTC, fedegl commented on app/assets/stylesheets/fe_modal.scss
> +    width: 408px;
define estas variables al principio de este archivo. e.g

```
$narrow-size: 25rem;
$medium-size: 40rem;
$wide-size: 50rem;
$extra-wide: 70rem;
```

2021-11-18 02:26 UTC, fedegl commented on javascript/src/controllers/remote-modal-controller.js
> +    this.isClass = target.getAttribute('data-class')
porque `isClass`? no estas guardando un valor boleano. Un mejor nombre sería `contentClass`.

2021-11-18 02:29 UTC, fedegl commented on javascript/src/controllers/remote-modal-controller.js
> +    this.isClass = target.getAttribute('data-class')
olvida lo que dije, ni si quiere necesitamos agregar otro atributo nuevo, ya podemos pasarle classes con el `data-wrapper-class`

2021-11-18 02:31 UTC, fedegl commented on app/assets/stylesheets/fe_modal.scss
> +.modal-content.small {
aprovecha las herramientas de SASS para no tener que andar repitiendo codigo

```suggestion
.modal-content {  
  @include tablet {
     &.narrow {...}
     &.medium {...}
     &.wide {...}
     &.extra-wide {...}
  }
}
```

2021-11-18 02:32 UTC, fedegl commented on app/assets/stylesheets/fe_modal.scss
> +
en la línea 60 usar la variable de `$medium-size` en vez de tener hardcodeado los 640px

2021-11-18 02:33 UTC, fedegl requested changes
no necesitamos el attributo `data-class` porque el `attributo` `data-wrapper-class` le pone las classes al mismo elemento HTML.

2021-11-18 02:36 UTC, fedegl requested changes
Porfa corrige el linter de JS

2021-11-22 16:59 UTC, fedegl commented on javascript/src/controllers/remote-modal-controller.js
> +  openModal(content) {
esto es lo que ha de haber tronado en StandardJS

```suggestion
  openModal (content) {
```

2021-11-22 16:59 UTC, M4T4 commented on javascript/src/controllers/remote-modal-controller.js
> +  openModal(content) {
Ya lo arregle

2021-11-22 17:02 UTC, merged