create file size limit controller
Grupo-AFAL/frontend-helpers pull request #182
Opened 2022-02-21 18:09 UTC by Ivan96318

2022-02-21 22:50 UTC, alexisKinto commented on javascript/src/controllers/file-size-limit-controller.js
> +  chekLimit (event) {
```suggestion
  checkLimit (event) {
```

2022-02-21 22:51 UTC, alexisKinto commented on javascript/src/controllers/file-size-limit-controller.js
> +  chekLimit (event) {
```suggestion
      this.checkLimit
    )
  }

  checkLimit (event) {
```

2022-02-21 22:51 UTC, alexisKinto commented on javascript/src/controllers/file-size-limit-controller.js
> +      this.chekLimit.bind(this)
```suggestion
      this.checkLimit.bind(this)
```

2022-02-21 22:55 UTC, alexisKinto commented on lib/frontend_helpers/shared_form_builder_utils.rb
> +      options.with_defaults!(limit_in_mg: 1, 'data-file-size-limit-target': 'trixEditor')
```suggestion
      options.with_defaults!(megabyte_limit: 1, 'data-file-size-limit-target': 'trixEditor')
```

2022-02-21 22:55 UTC, alexisKinto commented on lib/frontend_helpers/shared_form_builder_utils.rb
> +                                    'file-size-limit-limit-value': options[:limit_in_mg] }) do
```suggestion
                                    'file-size-limit-limit-value': options[:megabyte_limit] }) do
```

2022-02-21 22:59 UTC, alexisKinto commented on lib/frontend_helpers/shared_form_builder_utils.rb
> +      options.with_defaults!(limit_in_mg: 1, 'data-file-size-limit-target': 'trixEditor')
Si quieres usar la abreviacion de Megabyte es MB

2022-02-21 23:04 UTC, alexisKinto commented on javascript/src/controllers/file-size-limit-controller.js
> +        `¡Los archivos adjuntos no deben superar ${this.limitValue} MB!`
Recuerda que FEH ponemos todo en Ingles, o estaria aun mejor poder proporcionar nuestro propio mensaje de alerta

2022-02-22 01:50 UTC, alexisKinto commented on javascript/src/controllers/file-size-limit-controller.js
> +  static values = { limit: Number, message: String }
```suggestion
  static values = { limit: Number, alertMessage: String }
```

2022-02-22 01:51 UTC, alexisKinto commented on javascript/src/controllers/file-size-limit-controller.js
> +  static values = { limit: Number, message: String }
Tal vez seria bueno ponerlo mas especifico que es un mensaje de alerta, que piensas?

2022-02-22 01:52 UTC, alexisKinto commented on lib/frontend_helpers/shared_form_builder_utils.rb
> +      @template.content_tag(:div,
```suggestion
      options.with_defaults!(mb_limit: 1, 'data-file-size-limit-target': 'trixEditor')
      options.with_defaults!(message: "Attachments must not exceed #{options[:mb_limit]} MB!")

      @template.content_tag(:div,
```

2022-02-22 17:53 UTC, Ivan96318 commented on javascript/src/controllers/file-size-limit-controller.js
> +  static values = { limit: Number, message: String }
Si, pero mas bien tendria que ser en el helper, porque el helper es lo que usas en el código

2022-02-22 17:57 UTC, Ivan96318 commented on lib/frontend_helpers/shared_form_builder_utils.rb
> +      @template.content_tag(:div,
No entiendo que me estas sugiriendo aquí. 🤔

2022-02-22 18:04 UTC, alexisKinto commented on lib/frontend_helpers/shared_form_builder_utils.rb
> +      @template.content_tag(:div,
Solo es un salto de linea

2022-02-22 19:29 UTC, alexisKinto approved these changes

2022-02-22 21:20 UTC, fedegl commented on javascript/src/controllers/file-size-limit-controller.js
> +export class FileSizeLimitController extends Controller {
Creo que un mejor nombre sería:

```suggestion
export class TrixAttachmentsLimitController extends Controller {
```

porque todo esto es específico al editor de Trix, esto no lo podrías usar en otro contexto

2022-02-22 21:22 UTC, fedegl commented on javascript/src/controllers/file-size-limit-controller.js
> +      window.alert(this.messageValue)
esto previene que el usuario pueda hacer submit a la forma?

2022-02-22 21:23 UTC, fedegl commented on javascript/src/controllers/file-size-limit-controller.js
> +      this.checkLimit
esto no va a funcionar, porque `this.checkLimit` es una diferente funcion a la que le pasaste en el `connect` con `this.checkLimit.bind(this)`. Al agregarle el `.bind(this)` eso efectivamente esta creando una nueva funcion

2022-02-22 21:24 UTC, fedegl commented on javascript/src/controllers/file-size-limit-controller.js
> +    )
```suggestion
    this.checkLimit = this.checkLimit.bind(this)
    this.trixEditorTarget.addEventListener(
      'trix-file-accept',
      this.checkLimit
    )
```

2022-02-22 21:25 UTC, fedegl commented on javascript/src/controllers/file-size-limit-controller.js
> +      this.checkLimit
con la sugerencia en la línea 8, esto ya funcionaría.

2022-02-22 21:27 UTC, fedegl commented on javascript/src/controllers/file-size-limit-controller.js
> +  checkLimit (event) {
aqui crearía un nuevo método que solo calcule el total y te lo regrese para separar los diferentes tareas que hace este método y mejorar la claridad del código.

Adicionalmente es mejor utilizar un approach funcional para el calculo de esos valores usando `reduce`, con esto evitas tener que crear variables intermedias.

2022-02-22 21:28 UTC, fedegl commented on javascript/src/controllers/file-size-limit-controller.js
> +  static targets = ['trixEditor']
puedes evitar tener que especificar un target si defines el controlador en el mismo elemento de trix

2022-02-22 21:28 UTC, fedegl requested changes
Si quieres mejor regresando juntos hacemos los cambios para explicarte más rapido

2022-02-22 23:17 UTC, fedegl approved these changes

2022-02-22 23:21 UTC, merged