Corrected undefined when selected item by click and backspace when empty
Grupo-AFAL/frontend-helpers pull request #24
Opened 2021-03-22 22:53 UTC by alexisKinto

2021-03-23 02:19 UTC, fedegl requested changes
Implement the changes we discussed

2021-03-24 21:53 UTC, rafaelcdelgado approved these changes
Nada mas revisa si hay problema con el const y let

2021-03-24 22:08 UTC, alexisKinto commented
> Nada mas revisa si hay problema con el const y let

No veo problema, lo cambie a let ya que puede que se cambie el item, y const no permitiria eso

2021-03-24 22:33 UTC, fedegl approved these changes
:shipit:

2021-03-24 22:35 UTC, merged

2021-03-25 02:31 UTC, fedegl commented on javascript/src/controllers/tags-controller.js
> +    if (itemName !== null) item = this.firstAvailableItem(itemName)
@rafaelcdelgado @alexisKinto 

hasta ahorita me va cayendo el 20, pero creo que esto se puede simplificar así:
```js
const item = this.firstAvailableItem(itemName || this.inputTarget.value)
```